### ISSUE TITLE
FranceP2P Logo + Basic website

### ISSUE THREAD

**Issue by moul** [parisp2p/community#12]
We need a logo and a website for the meta "mother organization"

It can be very basic, as the main role of "FranceP2P" is to aggregate the regional chapters

It's more like a "router website"

**Comment by alexsland** [comment]
Logo proposal for France P2P :

![france_p2p_blue](https://user-images.githubusercontent.com/5212487/63607801-a6e04e00-c5d3-11e9-8851-e2332a1613b9.png)
![france_p2p_white](https://user-images.githubusercontent.com/5212487/63607802-a6e04e00-c5d3-11e9-8017-2943dc0767d7.png)
![france_p2p_red](https://user-images.githubusercontent.com/5212487/63607803-a6e04e00-c5d3-11e9-85c9-b6b35bd65e5a.png)


https://github.com/parisp2p/community/pull/34

**Comment by moul** [comment]
New repo and issue created here: parisp2p/francep2p.org#1

**Comment by moul** [comment]
Done here: https://github.com/parisp2p/francep2p.org/pull/2 :)
