### ISSUE TITLE
Setup a Proposal/Voting System

### ISSUE THREAD

**Issue by moul** [parisp2p/community#13]
It would be nice to allow people to publicly propose topics, talks, etc 

Then, to allow people to vote (👍, :-1:) so we can collectively take decisions
* as small as choosing a workshop topic to discuss in the next event
* or as big as taking important decisions for the community

For now, my favorite idea is to dedicate a GitHub repo so people can create issues for each new idea or suggestion, then, we can use the 👍 and :-1: voting option directly implemented inside GitHub; by using Issues Label, we can easily identify the different domains (workshop idea, tooling idea, etc)
We can try to start by staying in this repo and only move to a dedicated one if it becomes too noisy

What do you think? Any suggestions?

**Comment by Maniarr** [comment]
Rust Toulouse Meetup has this system for their [CFP](https://github.com/Rust-Toulouse/CFP).
It is also based on issues with template, very convenient.

**Comment by catwell** [comment]
+1 for using GitHub.

**Comment by moul** [comment]
Done

See #19 for the template, and #21 for a first example
