### ISSUE TITLE
Paris P2P #0

### ISSUE THREAD

**Issue by moul** [parisp2p/community#14]
## Info

* Meetup Link: https://www.meetup.com/fr-FR/Paris-P2P/events/263089573

## Slides:

* Event intro:
  * https://docs.google.com/presentation/d/1ejMJw9a82KojRiMLNyzgulC7UQLCZvnlVvBIqCghFN0
* Talk 1: History & Current State of P2P, by @moul 
  * https://docs.google.com/presentation/d/1EASD86eqXRVhB_rLGqVvsWJ2l_Pl9hRbmXIB5wqFvzE

**Comment by moul** [comment]
Debrief: 

* We need to find a solution for the loudness
  * Dedicated (silent) room for the beginning of the event?
  * Microphone + speakers?
* A lot of people have ideas about the community, the event etc, so we need to encourage people to open issues/discussions here or on Discord :)
* Quite good event for a first one, a lot of interesting people and discussions <3

Closing the issue as this event is "done", however, feel free to add comment, especially for suggesting improvements!

**Comment by catwell** [comment]
Small question: why Discord for the chat room and not a decentralized solution (e.g. Matrix)?

**Comment by moul** [comment]
> Small question: why Discord for the chat room and not a decentralized solution (e.g. Matrix)?

We chose Discord because it was the current trend for community chat solutions

Matrix allows bridging multiple solutions, we should setup the bridge to allow people to choose their favorite solution; anyone can help on this? (will create an issue)

> Also, the "event intro" doc is not properly shared (requires authorization).

Fixed! thx

> Otherwise: great event, will attend again. :)

🍾 see you there :)
