### ISSUE TITLE
Set up Matrix + bridge between Matrix and Discord

### ISSUE THREAD

**Issue by moul** [parisp2p/community#15]
Does someone have experience with the setup? Actually, I reserved the Matrix channels

Related with #14 

cc @catwell

**Comment by moul** [comment]
current channel: https://matrix.to/#/!zdSfRwwdOjzsjRzbsv:matrix.org?via=matrix.org

**Comment by catwell** [comment]
I use Matrix but I don't have experience with bridging. [It does not look too complicated.](https://t2bot.io/discord/)

**Comment by catwell** [comment]
Trying to join the channel on Riot, it doesn't work. Did you do anything weird with the configuration? Also, did you not choose a human-readable name on purpose?

![Screenshot from 2019-08-08 17-02-37](https://user-images.githubusercontent.com/221332/62714163-51664780-b9fe-11e9-92ec-6da5b65a013c.png)
![Screenshot from 2019-08-08 17-02-47](https://user-images.githubusercontent.com/221332/62714165-51664780-b9fe-11e9-8b37-a4981ade61fd.png)

**Comment by moul** [comment]
I updated the settings, here is the new invite link:

https://matrix.to/#/!gcnyCpTSlGiqqwphSu:matrix.org?via=matrix.org

you can also join directly using `/join #parisp2p`

**Comment by moul** [comment]
Bridge is working!

Thank you @catwell <3
