### ISSUE TITLE
[Talk Proposal] IPFS from A to Y

### ISSUE THREAD

**Issue by Jorropo** [parisp2p/community#80]
#### Title

IPFS from A to Y.

#### Languages

- [X] 🇫🇷
- [ ] 🇬🇧

#### Estimated duration

15min ~ 25min

#### Required knowledge level

| Network      | Cryptography | Blockchain   | General Tech |
| ------------ | ------------ | ------------ | ------------ |
| [ ] None     | [ ] None     | [X] None     | [X] None     |
| [X] Beginner | [X] Beginner | [ ] Beginner | [ ] Beginner |
| [ ] Advanced | [ ] Advanced | [ ] Advanced | [ ] Advanced |
| [ ] Expert   | [ ] Expert   | [ ] Expert   | [ ] Expert   |

#### Video recording

- [ ] Yes (mandatory)
- [X] Yes (if possible)
- [ ] No

---

## Description of your talk

- Will specific technos be discussed / presented? If so, which ones?
  [ipfs.io](https://ipfs.io/) the main goal
  [libp2p.io](https://libp2p.io/) explaining dht and rough transport
  [multiformats.io](https://multiformats.io/) protocols and cid, mainly to explain (what `/ip4/192.168.0.25/udp/4001/quic/ipfs/bafFoo`) and `/ipfs/Qmfoo` means.
  [ipld.io](https://ipld.io/)
- Will you present a project? If so, is it yours / are you part of the team leading it or not? Is it an open-source project? A commercial project? At what stage of its realization is it? etc...
  Yes, I'm a regular contributor and I'm not affiliated with protocols labs, ipfs is the tech backing filecoin (a blockchain CDN service (ipfs is the CDN part))
- To what extent do you intend to explore the topics covered?
  My goal is to give anyone the keys to understand ipfs what a file goes trough, The goal is not to be an expert of ipfs but what are the importants composants and why does this matters (like dht is not blockchain).

The 2 simple requirements are :
- Knowing what is internet (a network of stuff) and how it can be used (sending stuff to other people) (I think anyone likely to see this talk already knows this).
- And what is hashing and what does that implies (I can explain in one slide what is it fastly but that would be better if peoples have a rough understanding of it can be used and what does that implies for security (I think there is a huge gap beetween knowing that a one way function providing gibberish data in a predictable maner to this can be used in proof, security, handshakes, ...))

You can also provide a plan of the presentation by chapter.
- IPFS in one sentance (IPFS is a distributed content addressed CDN.) (explaining each glossary word)
- The journey of a file in the IPFS network :
  - API (very fly over)
  - IPLD how the file is cut and hashed
  - Bitswap how blocks are exchanged
  - DHT (main subject)
    - Libp2p modularity (mainly to explain how it was though, and how devs can choose very different things fullfilling their needs)
  - and the same faster in the way back on the receiving side.
- A few example use cases

---

## About you

* Discord handle: `Elpranocotro#4529`
* Links to your previous talks: none
* Other (your projects, etc...): I don't think that fits in the subject, my goal is really to explain a technology wich I hope is gonna be widely relevent.
* Availability (monthly number, date): mid august or later.

**Comment by zxxma** [comment]
Validated & scheduled for the online P2P meet-up @ dec, 2, 2020 !

**Comment by moul** [comment]
-> https://p2p.paris/en/talks/ipfs-ay/

Thank you @Jorropo \o/

**Comment by Jorropo** [comment]
Was done.

**Comment by zicmama** [comment]
@Jorropo is there a link where I could see the talk? Thx

**Comment by zxxma** [comment]
Sorry @zicmama no record this time
